name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
        
      - name: Setup GIT
        run: |
          git reset --hard
          git config --local --list
          git checkout main
          git config user.email "wezz@wezz.se"
          git config user.name "Wezz Balk"
        env:
            GH_EMAIL: ${{secrets.GH_EMAIL}}
          
      - name: Bump version
        run: |
          git reset --hard
          npm version patch
          npm run build
          git add . || true
          git commit -m "Build update" || true
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: npm publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm run trypublish
        env:
            NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
